---
- hosts: "{{ cluster }}.doris_hosts"
  remote_user: root
  vars_files:
    - ../conf/setup_vars.yml
    - ../conf/{{ cluster }}.yml
  tasks:
  - name: decompress all Doris Software packages
    unarchive:
      src: "{{ doris_filepath }}"
      dest: "{{ dest_filepath }}"
      copy: yes
  - name: mkdir meta 
    file: 
      path: "{{ doris_home }}/fe/meta"
      state: directory
  - name: mkdir storage
    file: 
      path: "{{ doris_home }}/be/storage"
      state: directory
  - name: scp fe.conf 
    copy: 
      src: "{{ fe_conf_path }}"
      dest: "{{ doris_home }}/fe/conf/"
      force: yes
  - name: scp be.conf
    copy: 
      src: "{{ be_conf_path }}"
      dest: "{{ doris_home }}/be/conf/"
      force: yes
  - name: export java home for start_fe
    lineinfile: 
      path: "{{ doris_home }}/fe/bin/start_fe.sh"
      insertafter: "# java"
      line: "export JAVA_HOME={{ java_home }}"
  - name: export java home for broker
    lineinfile:
      path: "{{ doris_home }}/apache_hdfs_broker/bin/start_broker.sh"
      insertafter: "# java"
      line: "export JAVA_HOME={{ java_home }}"

- hosts: "{{ cluster }}.master"
  remote_user: root
  vars_files: 
    - ../conf/setup_vars.yml
    - ../conf/{{ cluster }}.yml
  tasks:
    - name: module
      shell: echo "priority_networks=x"
      register: Fe
    - name: add fe.conf
      lineinfile:
        dest: "{{ fe_conf_path }}"
        line: "{{ Fe.stdout | replace('x',feconf) }}"
    - name: start master
      shell:
        cmd: 
          sh {{ doris_home }}/fe/bin/start_fe.sh --daemon

- hosts: "{{ cluster }}.follower"
  remote_user: root
  vars_files:
    - ../conf/setup_vars.yml
    - ../conf/{{ cluster }}.yml
  tasks:
    - name: module
      shell: echo "priority_networks=x"
      register: Fe
    - name: add fe.conf
      lineinfile:
        dest: "{{ fe_conf_path }}"
        line: "{{ Fe.stdout | replace('x',feconf) }}"
    - name: start follower
      shell:
        cmd: "sh {{ doris_home }}/fe/bin/start_fe.sh --helper {{ master }}:{{ edit_log_port }} --daemon"

- hosts: "{{ cluster }}.backends"
  remote_user: root
  vars_files:
    - ../conf/setup_vars.yml
    - ../conf/{{ cluster }}.yml
  tasks:
    - name: module
      shell: echo "priority_networks=x"
      register: Be
    - name: add be.conf
      lineinfile:
        dest: "{{ be_conf_path }}"
        line: "{{ Fe.stdout | replace('x',beconf) }}"
    - name: start all backends
      shell:
        cmd: "sh {{ doris_home }}/be/bin/start_be.sh --daemon"

- hosts: "{{ cluster }}.brokers"
  remote_user: root
  vars_files:
    - ../conf/setup_vars.yml
    - ../conf/{{ cluster }}.yml
  tasks:
    - name: start all brokers
      shell:
        cmd: "sh {{ doris_home }}/apache_hdfs_broker/bin/start_broker.sh --daemon"
